export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'lOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
export const HIDE_NOTIFICATION_DRAWER = 'HIDE_NOTIFICATION_DRAWER';
